### ISSUE TITLE
EABI support

### ISSUE THREAD

**Issue by modulo7** [remobjects/pascalscript#111]
I have started implementing ARM EABI support for pascalscript. Work so far can be found at https://github.com/modulo7/pascalscript

Changes:
    * Implement aligned passing of 64-bit parameters for EABI/EABIHF.
    * Implement passing of floating point parameters in vfp registers for EABIHF
    * Rewrite return value handling to avoid passing pointers to unsafe stack
      space.
    * Use constref on parameters to assembler to ensure passing by reference

Todo/issues:
    * Only lightly tested, far more testing needed.
    * Only EABIHF has been tested so far
    * Handling of floating point return types needs implementing for old abi
      FPA (the usual variant of old ABI).
    * String return code looks dubious, may leak memory. Testing needed.
    * Dynamic array return code was not reimplemented in the new return
      value handling. The old code doesn't look like it ever worked.

**Comment by carlokok** [comment]
How is this different from the (contributed) arm support already there?

**Comment by plugwash** [comment]
There are multiple different procedure call ABIs in use on arm32 and on arm more widely. If pascalscript is to correctly call native functions it needs to implement the right one.  For compatibility with non-pascal native code freepascal will nearly always use the same ABI as the linux system it is running on and so pascalscript also needs to use that ABI.

Afaict there are three main ABIS that have been used on arm32 plaforms that freepascal supports.

The old ABI (now reffered to as OABI). This was widely used in the past but is now considered largely historic. Debian had a port called "arm" which used this ABI from Debian 2.2 potato through to Debian 5.0 lenny. I belive other linux distros of similar vintage did too. I'm pretty sure wince also used this ABI.

The baseline variant of EABI (a newer ABI defiined by arm), also reffered to as "EABI soft float" since it doesn't use floating point registers for parameter passing or return values. Debian has a port called armel which uses this ABI. They added this port in 5.0 lenny and it is still maintained. Ubuntu also had a port which used this ABI but later dropped it. Android also initially used this ABI.

The "vfp register arguments" variant of eabI also reffered to as EABI hard float or EABIHF which passes floating point values in vfp registers. Debian has a port called armhf which uses this ABI which was introduced with Debian 7.0 (wheezy). This ABI is also used by Raspbian and recent versions of Ubuntu. I think android uses this ABI now too but i'm not sure of the details there.

Note: freepascal 2.6.x upstream does not have EABIHF support but freepascal trunk does and the Debian and Raspbian packages of freepascal 2.6.x have a backport of the EABIHF support.

The existing pascalscript arm port was for old ABI (EABI support is listed as a "todo") and hence will not work correctly in most current arm linux systems. modulo7 and I are working to resolve that. Along the way we ran into unsafe use of stack memory in the return value code and while we were fixing that we ran into issues related to ansistring and dynamic array return values which we are in the process of fixing.

Further reading

**Comment by carlokok** [comment]
ah so this would work best if it was defined for fpc on whatever the next version define will be?

**Comment by modulo7** [comment]
"ah so this would work best if it was defined for fpc on whatever the next version define will be?"
No, EABI baseline support has been in freepascal for some time. EABI hardfloat support isn't in an upstream stable release yet but is carried as a distribution patch by Debian, Ubuntu and Raspbian. So being able to build pascalscript correctly with their patched 2.6.x compilers is useful.

There are predefined #defines to identify the ABI the compiler is building for, so there is no need to use compiler version conditionals.

We have done more testing on old ABI, EABI baseline and EABI hardfloat (all with fpc 2.6.x) and have not found any regressions. The only outstanding issue we are aware of now is a memory leak in some circumstances involving dynamic array return values but since dynamic array return values were completely broken on arm before so this is an improvement on the previous situation.

"I'm presuming you want me to merge this in a pull request once this is done."
Yes, a pull request will follow shortly.

**Comment by carlokok** [comment]
nice work! thanks!
